version: 2
jobs:
  build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd crud-empresa && ./gradlew clean build --refresh-dependencies
  deploy:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    steps:
      - checkout
      - run:
          name: Create jar
          command: cd crud-empresa && ./gradlew bootJar
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
